_core:
  default_config_hash: Dy0eQlnGPF7PYN3XkrnJyk2bh4L195ZSzCbWLTV-HS4
langcode: de
prompts:
  complete: ''
  modify_prompt: "Verwenden Sie die folgenden Anweisungen, um diesen Text zu bearbeiten. Geben Sie nur den bearbeiteten Text ohne Erläuterungen zurück.\r\nAnweisungen: {{ modify_prompt }}\r\nZu verarbeitender Text:\n"
  reformat: |
    Wählen Sie mindestens ein AI-Anbietermodul aus der Liste auf der AI-Modul-Homepage aus, fügen Sie es zu Ihrem Projekt hinzu, installieren und konfigurieren Sie es. Aktualisieren Sie dann die AI-Einstellungen auf dieser Seite.
  spellfix: |
    Bitte richten Sie diesen Text so ein, dass er mit semantischem HTML markiert ist und nur Listen, Überschriften oder Absatz-Tags verwendet:
  summarise: "Fasse den folgenden Text in der gleichen Sprache zusammen,\r\nGib den Originaltext nicht wieder und gib ihn nicht Wort für Wort wieder.\r\n\r\nHier ist der Originaltext:\n"
  tone: |
    Change the tone of the following text to be {{ tone }} using the same language as the following text.
  translate: "Reagieren Sie nicht, sondern antworten Sie nur mit dem übersetzten Text, keine Höflichkeiten.\r\nÜbersetzen Sie den folgenden Text in {{ lang }}\n"
