name: Blog
type: adesso CMS
description: 'Sets up a basic blog, with tagging.'
recipes:
  - drupal_cms_blog
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
