name: adesso CMS Content
description: Installs default content including images, media, nodes, and navigation for the adesso CMS.
type: Site
recipes:
  - adesso_cms_paragraphs
install:
  - default_content
config:
  strict: false