name: 'adesso CMS AI Integration'
description: 'Comprehensive AI integration for content generation, moderation, and enhancement.'
type: 'Site'

install:
  # AI Core
  - ai
  - ai_logging
  
  # AI Providers
  - ai_provider_openai
  - ai_provider_anthropic
  - ai_provider_groq
  
  # AI Features
  - ai_agents
  - ai_agents_explorer
  - ai_agents_extra
  - ai_agents_form_integration
  - ai_api_explorer
  - ai_assistant_api
  - ai_automators
  - ai_chatbot
  - ai_ckeditor
  - ai_content_suggestions
  - ai_eca
  - ai_external_moderation
  - ai_image_alt_text
  - ai_image_bulk_alt_text
  - ai_search
  - ai_seo
  - ai_translate
  
  # Required dependencies
  - key

config:
  strict: false
  import:
    ai: '*'
    ai_logging: '*'
    ai_provider_openai: '*'
    ai_provider_anthropic: '*'
    ai_provider_groq: '*'
    ai_agents: '*'
    ai_assistant_api: '*'
    ai_ckeditor: '*'
    ai_content_suggestions: '*'
    ai_external_moderation: '*'
    ai_image_alt_text: '*'
    ai_translate: '*'
    key: '*'
    klaro:
      - klaro.klaro_app.ai_alt_text_generation
    image:
      - image.style.ai_image_alt_text
    views:
      - views.view.ai_logs
    block:
      - block.block.ai_chatbot
      
  actions:
    # Configure AI providers with secure key management
    ai_provider_openai.settings:
      simpleConfigUpdate:
        api_key: '[key:openai_api_key]'
        model: 'gpt-4o'
        temperature: 0.7
        max_tokens: 2000
        
    ai_provider_anthropic.settings:
      simpleConfigUpdate:
        api_key: '[key:anthropic_api_key]'
        model: 'claude-3-5-sonnet-20241022'
        temperature: 0.7
        max_tokens: 4000
        
    ai_provider_groq.settings:
      simpleConfigUpdate:
        api_key: '[key:groq_api_key]'
        model: 'llama-3.1-70b-versatile'
        temperature: 0.7
        max_tokens: 2000
        
    # Configure AI content suggestions
    ai_content_suggestions.settings:
      simpleConfigUpdate:
        enabled_bundles:
          - page
          - news
          - person
          - project
          - event
        default_provider: 'anthropic'
        suggestions_per_field: 3
        auto_generate: false
        
    # Configure AI image alt text generation
    ai_image_alt_text.settings:
      simpleConfigUpdate:
        enabled: true
        provider: 'openai'
        auto_generate: true
        backup_provider: 'anthropic'
        quality_threshold: 0.8
        
    # Configure AI translation
    ai_translate.settings:
      simpleConfigUpdate:
        enabled: true
        provider: 'anthropic'
        supported_languages:
          - de
          - en
          - fr
          - es
        auto_detect: true
        
    # Configure AI external moderation
    ai_external_moderation.settings:
      simpleConfigUpdate:
        enabled: true
        provider: 'openai'
        moderate_content: true
        moderate_comments: true
        block_inappropriate: true
        
    # Configure AI logging
    ai_logging.settings:
      simpleConfigUpdate:
        log_requests: true
        log_responses: true
        retention_days: 30
        privacy_mode: true
        
    # Grant permissions to content editors
    user.role.content_editor:
      grantPermissions:
        - 'use ai content suggestions'
        - 'generate ai image alt text'
        - 'use ai translation'
        - 'access ai chatbot'
        - 'view ai logs'
        
    # Grant AI administration permissions to administrators
    user.role.administrator:
      grantPermissions:
        - 'administer ai'
        - 'administer ai providers'
        - 'manage ai agents'
        - 'configure ai moderation'
        - 'view detailed ai logs'
        - 'bulk generate alt text'