entity_types:
  node:
    - page
  paragraph:
    - card
    - grid
    - hero
    - image_text
    - text
sidebar_width: 30
full_width: 70
ajax_content_update: true
hover_highlight: true
exclude_fields: {  }
automatic_preview: false
primary_color: '#0081c9'
ui_toggle: true
ui_toggle_settings:
  offset_top: ''
  offset_bottom: '50'
  offset_left: ''
  offset_right: '50'
duplicate_action_links:
  height: 300
action_links_in_viewport: _none
