content_root: ''
assertiveness: assertive
no_load: ''
ignore_all_if_absent: ''
ignore_elements: '.leaflet-map-pane *'
panel_no_cover: ''
embedded_content_warning: ''
download_links: ''
link_strings_new_windows: ''
ignore_link_strings: ''
link_ignore_selector: 'svg.ext, svg.mailto, .link-purpose-text'
hidden_handlers: ''
element_hides_overflow: ''
ed11y_theme: sleekTheme
panel_pin: right
shadow_components: ''
detect_shadow: false
watch_for_changes: checkRoots
disable_sync: false
preserve_params: 'search,keys,page,language,language_content_entity'
redundant_prefix: ''
custom_tests: 0
disable_live: false
live_h_inherit: ''
live_h2: 'form[id^="node-"] #edit-body-wrapper .ck-content'
live_h3: ''
live_h4: ''
hide_edit_links: ''
ck5_table_headers: row
ignore_tests: {  }
