enabled:
  block_content:
    social_media: default
  content_moderation_state:
    content_moderation_state: default
  crop:
    focal_point: default
  paragraph:
    accordion: default
    accordion_item: default
    block_reference: default
    bullet: default
    card: default
    card_group: default
    carousel: default
    carousel_item: default
    download: default
    download_item: default
    embed: default
    gallery: default
    hero: default
    logo_collection: default
    media: default
    newsletter: default
    pricing: default
    pricing_card: default
    sidebyside: default
    slider: default
    slider_item: default
    stats_item: default
    text: default
    views: default
    webform_embed: default
