name: adesso CMS
description: Applies all the basic adesso CMS recipes.
type: Site
recipes:
  - core/recipes/tags_taxonomy
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_seo_basic
  - easy_email_express
  - drupal_cms_authentication
  - drupal_cms_privacy_basic
  - drupal_cms_remote_video
  - drupal_cms_seo_tools
  - drupal_cms_accessibility_tools
  - drupal_cms_forms
  - adesso_cms_paragraphs
install:
  - node
  - datetime_range
  - components
  - address
  - geofield
  - metatag
  - viewfield
  - yoast_seo
  - smart_date
  - leaflet
  - field_ui
  - responsive_image
  - automatic_updates
  - automatic_updates_extensions
  - dashboard
  - menu_link_content
  - package_manager
  - project_browser
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - menu_ui
  - shortcut
  - views_ui
  - twig_field_value
  - svg_image
  - svg_image_responsive
  - default_content
  - preview
  - frontend_editing
  - adesso_cms_theme
  - allowed_formats
  # Search API modules
  - search_api
  - search_api_autocomplete
  - search_api_db
  - search_api_exclude
  - block
  - layout_builder
  - ckeditor5
  - config
  - content_moderation
  - help
  - contextual
  - datetime
  - datetime_range
  - editor
  - field_ui
  - file
  - history
  - image
  - language
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - shortcut
  - taxonomy
  - views
  - views_ui
  - field_group
  - linkit
  - metatag
  - node_revision_delete
  - pathauto
  - paragraphs
  - paragraphs_features
  - redirect
  - responsive_image
  - svg_image
  - svg_image_responsive
  - viewfield
  - block_content
  - twig_tweak
  - webp
  - webform
  - webform_ui
  # File upload enhancements
  - dropzonejs
  - dropzonejs_eb_widget
  - entity_browser
  # Additional modules from core.extension.yml
  - add_content_by_bundle
  - announcements_feed
  - automated_cron
  - autosave_form
  - better_exposed_filters
  - big_pipe
  - bpmn_io
  - breakpoint
  - captcha
  - checklistapi
  - coffee
  - crop
  - dblog
  - dynamic_page_cache
  - easy_breadcrumb
  - easy_email
  - easy_email_override
  - eca
  - eca_base
  - eca_config
  - eca_content
  - eca_misc
  - eca_modeller_bpmn
  - eca_render
  - eca_ui
  - eca_user
  - editoria11y
  - entity_reference_revisions
  - field
  - filter
  - focal_point
  - friendlycaptcha
  - gin_toolbar
  - honeypot
  - jquery_ui
  - jquery_ui_resizable
  - klaro
  - mailsystem
  - menu_link_attributes
  - metatag_open_graph
  - metatag_twitter_cards
  - mysql
  - navigation
  - page_cache
  - paragraphs_edit
  - paragraphs_ee
  - path_alias
  - redirect_404
  - robotstxt
  - sam
  - scheduler
  - scheduler_content_moderation_integration
  - search
  - seo_checklist
  - simple_search_form
  - simple_sitemap
  - sitemap
  - symfony_mailer_lite
  - system
  - telephone
  - text
  - token
  - token_or
  - trash
  - update
  - user
  - vite
  - workflows
  - yoast_seo
  - selective_better_exposed_filters
  - content_translation
  - status_messages
  - media_bulk_upload
  - media_bulk_upload_dropzonejs

config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    # Import ALL configurations to ensure 1:1 reproduction
    adesso_cms_theme: '*'
    announcements_feed: '*'
    automated_cron: '*'
    automatic_updates: '*'
    autosave_form: '*'
    block: '*'
    block_content: '*'
    captcha: '*'
    claro: '*'
    coffee: '*'
    crop: '*'
    dashboard: '*'
    dblog: '*'
    dropzonejs: '*'
    easy_breadcrumb: '*'
    easy_email: '*'
    easy_email_override: '*'
    eca: '*'
    editor: '*'
    editoria11y: '*'
    entity_browser: '*'
    field: '*'
    field_group: '*'
    filter: '*'
    focal_point: '*'
    friendlycaptcha: '*'
    gin: '*'
    gin_toolbar: '*'
    honeypot: '*'
    image: '*'
    jquery_ui: '*'
    klaro: '*'
    language: '*'
    leaflet: '*'
    linkit: '*'
    login_emailusername: '*'
    mailsystem: '*'
    media: '*'
    menu_link_attributes: '*'
    metatag: '*'
    navigation: '*'
    node: '*'
    node_revision_delete: '*'
    olivero: '*'
    paragraphs: '*'
    paragraphs_edit: '*'
    paragraphs_ee: '*'
    paragraphs_features: '*'
    pathauto: '*'
    redirect: '*'
    responsive_image: '*'
    robotstxt: '*'
    sam: '*'
    scheduler: '*'
    search_api: '*'
    seo_checklist: '*'
    shortcut: '*'
    simple_search_form: '*'
    simple_sitemap: '*'
    sitemap: '*'
    svg_image: '*'
    svg_image_responsive: '*'
    symfony_mailer_lite: '*'
    system: '*'
    tagify: '*'
    taxonomy: '*'
    token: '*'
    token_or: '*'
    trash: '*'
    twig_field_value: '*'
    twig_tweak: '*'
    user: '*'
    viewfield: '*'
    views: '*'
    views_ui: '*'
    webform: '*'
    webp: '*'
    workflows: '*'
    yoast_seo: '*'
    media_bulk_upload: '*'
  actions:
    frontend_editing.settings:
      simpleConfigUpdate:
        entity_types:
          paragraph:
            - accordion
            - block_reference
            - bullet
            - card
            - card_group
            - carousel
            - download
            - embed
            - gallery
            - hero
            - logo_collection
            - media
            - newsletter
            - pricing
            - sidebyside
            - slider
            - text
            - views
        hover_highlight: false
        primary_color: '#0081c9'
        automatic_preview: true
    package_manager.settings:
      simpleConfigUpdate:
        additional_trusted_composer_plugins:
          # This is indirectly added by `drupal/core-dev`.
          - tbachert/spi
    project_browser.admin_settings:
      simpleConfigUpdate:
        allowed_projects:
          recipes:
            - drupal_cms_accessibility_tools
            - drupal_cms_blog
            - drupal_cms_case_study
            - drupal_cms_events
            - drupal_cms_forms
            - drupal_cms_news
            - drupal_cms_person
            - drupal_cms_project
            - drupal_cms_search
            - drupal_cms_seo_tools
        enabled_sources:
          - drupalorg_jsonapi
          - recipes
        allow_ui_install: true
    system.site:
      simpleConfigUpdate:
        name: 'adessoCMS'
        page.front: '/welcome-adesso-cms'
    system.theme:
      simpleConfigUpdate:
        default: adesso_cms_theme
    gin.settings:
      simpleConfigUpdate:
        preset_accent_color: custom
        accent_color: '#0080c9'
    navigation.settings:
      simpleConfigUpdate:
        logo:
          provider: custom
          path: profiles/adesso_cms_installer/images/logo.png
          max:
            filesize: 1048576
            height: 40
            width: 40
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'create page content'
        - 'delete page revisions'
        - 'delete any page content'
        - 'edit any page content'
        - 'access administration pages'
        - 'access content overview'
        - 'access contextual links'
        - 'access media overview'
        - 'access navigation'
        - 'administer url aliases'
        - 'create url aliases'
        - 'view own unpublished media'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view the administration theme'
        - 'use text format basic_html'
        - 'use text format full_html'
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'access shortcuts'
        - 'delete own files'
        - 'view own unpublished content'
        - 'view welcome dashboard'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    announcements_feed.settings:
      simpleConfigUpdate:
        limit: 2
    core.menu.static_menu_link_overrides:
      simpleConfigUpdate:
        definitions.announcements_feed__announcement:
          menu_name: admin
          parent: system.admin
          weight: 0
          expanded: false
          enabled: false
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    # Enable development mode - disable CSS/JS aggregation
    system.performance:
      simpleConfigUpdate:
        css.preprocess: false
        js.preprocess: false
    # Set metatag defaults.
    metatag.metatag_defaults.global:
      simple_config_update:
        tags.canonical_url: '[current-page:url]'
        tags.title: '[current-page:title] | [site:name]'
    metatag.metatag_defaults.node:
      simple_config_update:
        tags.abstract: '[node:summary]'
        tags.canonical_url: '[node:url]'
        tags.description: '[node:summary]'
    field.field.node.page.field_paragraphs:
      simpleConfigUpdate:
        label: Inhaltselemente
        description: 'Fügen Sie Inhaltselemente wie Text, Bilder, Galerien und andere Komponenten hinzu, um Ihre Seite zu gestalten.'
        settings.handler_settings.target_bundles:
          accordion: accordion
          block_reference: block_reference
          card_group: card_group
          carousel: carousel
          download: download
          embed: embed
          gallery: gallery
          hero: hero
          logo_collection: logo_collection
          media: media
          newsletter: newsletter
          pricing: pricing
          sidebyside: sidebyside
          slider: slider
          text: text
          views: views
        settings.handler_settings.target_bundles_drag_drop.logo_collection.enabled: true
        settings.handler_settings.target_bundles_drag_drop.embed.enabled: true
        settings.handler_settings.target_bundles_drag_drop.download.enabled: true
        settings.handler_settings.target_bundles_drag_drop.block_reference.enabled: true
    core.entity_view_display.node.page.default:
      simpleConfigUpdate:
        content.field_paragraphs:
          type: entity_reference_revisions_entity_view
          label: hidden
          settings:
            view_mode: default
            link: ''
          third_party_settings: {}
          weight: 1
          region: content
        hidden.field_paragraphs: null
        hidden.field_featured_image: true
        content.field_featured_image: null
        third_party_settings.layout_builder.enabled: false
    core.entity_form_display.node.page.default:
      simpleConfigUpdate:
        content.field_paragraphs:
          type: paragraphs
          weight: 8
          region: content
          settings:
            title: Inhaltselement
            title_plural: Inhaltselemente
            edit_mode: open
            closed_mode: summary
            autocollapse: none
            autocollapse_default: all
            closed_mode_threshold: 0
            add_mode: dropdown
            form_display_mode: default
            default_paragraph_type: ''
            features:
              duplicate: duplicate
              collapse_edit_all: collapse_edit_all
              add_above: '0'
          third_party_settings: {}
        hidden.field_paragraphs: null
        hidden.layout_builder__layout: true
    workflows.workflow.basic_editorial:
      addNodeTypes: ['page']
    # Disable Layout Builder for all content types
    core.entity_view_display.node.landing_page.default:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.landing_page.card:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.landing_page.teaser:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.landing_page.search_index:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_form_display.node.landing_page.default:
      simpleConfigUpdate:
        hidden.layout_builder__layout: true
    # Disable Layout Builder for all other content types
    core.entity_view_display.node.event.card:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.event.default:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.event.teaser:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.news.card:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.news.default:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.news.teaser:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.news.search_index:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.person.card:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.person.default:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.person.teaser:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.person.search_index:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.project.card:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.project.default:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.project.teaser:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    core.entity_view_display.node.project.search_index:
      simpleConfigUpdate:
        third_party_settings.layout_builder.enabled: false
        third_party_settings.layout_builder.allow_custom: false
    # Hide layout builder fields in form displays
    core.entity_form_display.node.event.default:
      simpleConfigUpdate:
        hidden.layout_builder__layout: true
    core.entity_form_display.node.news.default:
      simpleConfigUpdate:
        hidden.layout_builder__layout: true
    core.entity_form_display.node.person.default:
      simpleConfigUpdate:
        hidden.layout_builder__layout: true
    core.entity_form_display.node.project.default:
      simpleConfigUpdate:
        hidden.layout_builder__layout: true
