name: AI
type: adesso CMS
description: Adds integration with AI services, such as alt text generation and a chat bot to assist with site building. Requires an API key from Open AI or Anthropic.

recipes:
  - drupal_cms_ai

install:
  - ai_provider_groq
