name: 'adesso CMS Page Header'
description: 'Configures page header display settings and field visibility for adesso CMS theme.'
type: 'Site'

config:
  strict: false
  actions:
    # Hide featured image from page content display (used in page header instead)
    core.entity_view_display.node.page.default:
      simpleConfigUpdate:
        hidden:
          field_featured_image: true
        content:
          field_featured_image: null