_core:
  default_config_hash: UugaWbt1B0Ne-89xe8rkNQjiIDGJNvxJrRrxUkYNAUk
langcode: en
status: true
dependencies: {  }
id: main-services
title: Services
description: ''
menu_name: main
link:
  uri: 'internal:/services'
  title: ''
  options: {  }
external: false
rediscover: false
weight: -49
expanded: true
enabled: true
parent: ''
changed: 1640995200
