_core:
  default_config_hash: DDeJcS5MvWxgtXqZW-9WKonhWOgGpOtF_8m-3I5agUw
langcode: en
status: true
dependencies: {  }
id: main-mobile-apps
title: 'Mobile Apps'
description: 'iOS and Android mobile applications'
menu_name: main
link:
  uri: 'internal:/services/mobile-apps'
  title: ''
  options: {  }
external: false
rediscover: false
weight: -47
expanded: false
enabled: true
parent: 'menu_link_content:main-services'
changed: 1640995200
