_core:
  default_config_hash: KgjbB8y3zolxqGJrw3_y2ZkpEE5Y4CT7SnRPi_2wExc
langcode: en
status: true
dependencies: {  }
id: main-home
title: Home
description: ''
menu_name: main
link:
  uri: 'internal:/'
  title: ''
  options: {  }
external: false
rediscover: false
weight: -50
expanded: false
enabled: true
parent: ''
changed: 1640995200
