name: adesso CMS
description: Applies all the basic adesso CMS recipes.
type: Site
recipes:
  - core/recipes/tags_taxonomy
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_seo_basic
  - easy_email_express
  - adesso_cms_paragraphs
install:
  - node
  - datetime_range
  - components
  - metatag
  - field_ui
  - responsive_image
  - automatic_updates
  - automatic_updates_extensions
  - dashboard
  - menu_link_content
  - package_manager
  - project_browser
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - menu_ui
  - shortcut
  - views_ui
  - twig_field_value
  - svg_image
  - svg_image_responsive
  - default_content
  - preview
  - frontend_editing
  - adesso_cms_theme
  - allowed_formats
  - ckeditor5
  - config
  - content_moderation
  - help
  - contextual
  - datetime
  - datetime_range
  - editor
  - field_ui
  - file
  - history
  - image
  - language
  - link
  - media
  - media_library
  - menu_link_content
  - menu_ui
  - node
  - options
  - path
  - shortcut
  - taxonomy
  - views
  - views_ui
  - field_group
  - linkit
  - metatag
  - node_revision_delete
  - pathauto
  - paragraphs
  - paragraphs_features
  - redirect
  - responsive_image
  - svg_image
  - svg_image_responsive
  - viewfield
  - block_content
  - twig_tweak
  - webp
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    adesso_cms_theme: '*'
    node: '*'
    navigation:
      - navigation.settings
    shortcut:
      - shortcut.set.default
    user:
      # This view mode is only needed because Olivero expects it to exist
      # in certain situations.
      - core.entity_view_mode.user.compact
      - views.view.user_admin_people
    content_moderation: '*'
    editor: '*'
    file: '*'
    field_ui: '*'
    media_library:
      - core.entity_view_mode.media.media_library
      - core.entity_form_mode.media.media_library
      - image.style.media_library
      - views.view.media_library
    media:
      - core.entity_view_mode.media.full
      - system.action.media_delete_action
      - system.action.media_publish_action
      - system.action.media_save_action
      - system.action.media_unpublish_action
      - views.view.media
    image:
      - image.style.medium
      - image.style.large
      - image.style.thumbnail
    menu_ui: '*'
    datetime: '*'
    datetime_range: '*'
    views: '*'
    views_ui: '*'
    #contrib
    field_group: '*'
    linkit: '*'
    metatag: '*'
    node_revision_delete: '*'
    pathauto: '*'
    paragraphs: '*'
    paragraphs_features: '*'
    redirect: '*'
    responsive_image: '*'
    svg_image: '*'
    svg_image_responsive: '*'
    viewfield: '*'
    webp: '*'
  actions:
    frontend_editing.settings:
      simpleConfigUpdate:
        entity_types:
          paragraph:
            - accordion
            - bullet
            - card
            - card_group
            - carousel
            - embed
            - gallery
            - hero
            - logo_collection
            - media
            - newsletter
            - pricing
            - sidebyside
            - slider
            - text
            - views
        hover_highlight: false
        primary_color: '#0081c9'
        automatic_preview: true
    package_manager.settings:
      simpleConfigUpdate:
        additional_trusted_composer_plugins:
          # This is indirectly added by `drupal/core-dev`.
          - tbachert/spi
    project_browser.admin_settings:
      simpleConfigUpdate:
        allowed_projects:
          recipes:
            - drupal_cms_accessibility_tools
            - adesso_cms_ai
            - drupal_cms_blog
            - drupal_cms_case_study
            - drupal_cms_events
            - drupal_cms_forms
            - drupal_cms_news
            - drupal_cms_person
            - drupal_cms_project
            - drupal_cms_search
            - drupal_cms_seo_tools
        enabled_sources:
          - drupalorg_jsonapi
          - recipes
        allow_ui_install: true
    system.site:
      simpleConfigUpdate:
        name: 'adesso CMS'
        page.front: '/welcome'
    system.theme:
      simpleConfigUpdate:
        default: adesso_cms_theme
    gin.settings:
      simpleConfigUpdate:
        preset_accent_color: custom
        accent_color: '#0080c9'
    navigation.settings:
      simpleConfigUpdate:
        logo:
          provider: custom
          path: profiles/adesso_cms_installer/images/logo.png
          max:
            filesize: 1048576
            height: 40
            width: 40
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'access administration pages'
        - 'access content overview'
        - 'access contextual links'
        - 'access media overview'
        - 'access navigation'
        # We need this permission because Toolbar is enabled by Gin Toolbar.
        - 'access toolbar'
        - 'administer url aliases'
        - 'create url aliases'
        - 'view own unpublished media'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view the administration theme'
        - 'use text format basic_html'
        - 'use text format full_html'
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'access shortcuts'
        - 'delete own files'
        - 'view own unpublished content'
        - 'view welcome dashboard'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    announcements_feed.settings:
      simpleConfigUpdate:
        limit: 2
    core.menu.static_menu_link_overrides:
      simpleConfigUpdate:
        definitions.announcements_feed__announcement:
          menu_name: admin
          parent: system.admin
          weight: 0
          expanded: false
          enabled: false
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
    # Set metatag defaults.
    metatag.metatag_defaults.global:
      simple_config_update:
        tags.canonical_url: '[current-page:url]'
        tags.title: '[current-page:title] | [site:name]'
    metatag.metatag_defaults.node:
      simple_config_update:
        tags.abstract: '[node:summary]'
        tags.canonical_url: '[node:url]'
        tags.description: '[node:summary]'
