name: adesso CMS
description: Applies all the basic adesso CMS recipes.
type: Site
recipes:
  - core/recipes/tags_taxonomy
  - core/recipes/core_recommended_maintenance
  - core/recipes/core_recommended_performance
  - core/recipes/document_media_type
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - drupal_cms_admin_ui
  - drupal_cms_anti_spam
  - drupal_cms_seo_basic
  - easy_email_express
  - ../recipes/drupalx-paragraphs
install:
  - node
  - datetime_range
  - components
  - metatag
  - field_ui
  - responsive_image
  - automatic_updates
  - automatic_updates_extensions
  - dashboard
  - menu_link_content
  - package_manager
  - project_browser
  # The rest of these are in Standard.
  - inline_form_errors
  - config
  - menu_ui
  - shortcut
  - views_ui
  - twig_field_value
  - svg_image
  - svg_image_responsive
  - default_content
  - all_entity_preview
  - frontend_editing
  - adesso_cms_theme
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  import:
    adesso_cms_theme: '*'
    node: '*'
    navigation:
      - navigation.settings
    linkit:
      - image.style.linkit_result_thumbnail
    image:
      - image.style.large
      - image.style.thumbnail
    shortcut:
      - shortcut.set.default
    user:
      # This view mode is only needed because Olivero expects it to exist
      # in certain situations.
      - core.entity_view_mode.user.compact
      - views.view.user_admin_people
  actions:
    frontend_editing.settings:
      simpleConfigUpdate:
        entity_types:
          node:
            - page
          paragraph:
            - card
            - grid
            - hero
            - image_text
            - text
        hover_highlight: true
        primary_color: '#0081c9'
    package_manager.settings:
      simpleConfigUpdate:
        additional_trusted_composer_plugins:
          # This is indirectly added by `drupal/core-dev`.
          - tbachert/spi
    project_browser.admin_settings:
      simpleConfigUpdate:
        allowed_projects:
          recipes:
            - drupal_cms_events
            - adesso_cms_blog
            - drupal_cms_case_study
            - drupal_cms_forms
            - drupal_cms_news
            - drupal_cms_person
            - drupal_cms_project
            - drupal_cms_seo_tools
            - drupal_cms_accessibility_tools
        enabled_sources:
          - drupalorg_jsonapi
          - recipes
        allow_ui_install: true
    system.site:
      simpleConfigUpdate:
        name: 'adesso CMS'
        page.front: '/home'
    system.theme:
      simpleConfigUpdate:
        default: adesso_cms_theme
    gin.settings:
      simpleConfigUpdate:
        preset_accent_color: custom
        accent_color: '#0080c9'
    navigation.settings:
      simpleConfigUpdate:
        logo:
          provider: custom
          path: profiles/adesso_cms_installer/images/logo.png
          max:
            filesize: 1048576
            height: 40
            width: 40
    user.role.content_editor:
      grantPermissionsForEachMediaType:
        - 'create %bundle media'
        - 'delete any %bundle media'
        - 'edit any %bundle media'
      grantPermissions:
        - 'access administration pages'
        - 'access content overview'
        - 'access contextual links'
        - 'access media overview'
        - 'access navigation'
        # We need this permission because Toolbar is enabled by Gin Toolbar.
        - 'access toolbar'
        - 'administer url aliases'
        - 'create url aliases'
        - 'view own unpublished media'
        - 'delete own files'
        - 'revert all revisions'
        - 'view all revisions'
        - 'view the administration theme'
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    user.role.authenticated:
      grantPermissions:
        - 'access shortcuts'
        - 'delete own files'
        - 'view own unpublished content'
        - 'view welcome dashboard'
    user.settings:
      simpleConfigUpdate:
        verify_mail: true
        register: admin_only
        cancel_method: user_cancel_block
    announcements_feed.settings:
      simpleConfigUpdate:
        limit: 2
    core.menu.static_menu_link_overrides:
      simpleConfigUpdate:
        definitions.announcements_feed__announcement:
          menu_name: admin
          parent: system.admin
          weight: 0
          expanded: false
          enabled: false
    automatic_updates.settings:
      simpleConfigUpdate:
        allow_core_minor_updates: true
