name: 'adesso CMS Paragraphs'
description: 'adesso CMS paragraph types.'
type: 'Site'

install:
  # Core
  - link
  - media
  - media_library
  - options
  - text
  # Contrib
  - paragraphs
  - paragraphs_features
  - paragraphs_ee
  - viewfield
