name: 'adesso CMS Paragraphs'
description: 'adesso CMS paragraph types.'
type: 'Site'

install:
  # Core modules
  - block_content
  - image
  - link
  - media
  - media_library
  - options
  - responsive_image
  - text
  - file
  # Contrib modules
  - focal_point
  - paragraphs
  - paragraphs_edit
  - entity_reference_revisions
  - crop
  - entity_browser
  - dropzonejs
  - dropzonejs_eb_widget
  - webform

config:
  strict: false
  import:
    # Import all paragraph types
    paragraphs: '*'
    # Import field configurations
    field: '*'
    # Import image styles and responsive image styles
    image: '*'
    responsive_image: '*'
    # Import crop configurations
    crop: '*'
    # Import paragraph categories
    paragraphs_ee: '*'
