name: 'adesso CMS Paragraphs'
description: 'adesso CMS paragraph types.'
type: 'Site'

install:
  # Core
  - block_content
  - image
  - link
  - media
  - media_library
  - options
  - responsive_image
  - text
  # Contrib
  - focal_point
  - paragraphs
  - paragraphs_features
  - viewfield
  - webp

config:
  import:
    # Import field_paragraphs configuration for basic page content type
    paragraphs:
      - field.field.node.page.field_paragraphs
