name: adesso CMS Paragraphs
description: Applies all the basic adesso CMS recipes.
type: Site
recipes:
  - drupal_cms_page
install:
  - adesso_standard
  - frontend_editing
  - storybook
  - ui_patterns
  - ui_patterns_layouts
  - ui_patterns_library
  - ui_patterns_field_formatters
  - ui_patterns_blocks
  - ui_patterns_views
config:
  # If the config we're importing already exists, we don't really care
  # what it looks like.
  strict: false
  actions:
    frontend_editing.settings:
      simpleConfigUpdate:
        entity_types:
          node:
            - page
          paragraph:
            - card
            - grid
            - hero
            - image_text
            - text
        hover_highlight: true
        primary_color: '#0081c9'
        sidebar_width: 30
        full_width: 70
        ajax_content_update: true
        exclude_fields: {  }
        automatic_preview: false
        ui_toggle: true
        ui_toggle_settings:
          offset_top: ''
          offset_bottom: 50
          offset_left: ''
          offset_right: 50
        duplicate_action_links:
          height: 300
        action_links_in_viewport: _none
    core.entity_form_display.node.page.default:
      setComponent:
        name: field_paragraphs
        options:
          type: paragraphs
          weight: 8
          region: content
          settings:
            title: Seitenabschnitt
            title_plural: Seitenabschnitte
            edit_mode: open
            closed_mode: summary
            autocollapse: none
            closed_mode_threshold: 0
            add_mode: dropdown
            form_display_mode: default
            default_paragraph_type: card
            features:
              add_above: '0'
              collapse_edit_all: collapse_edit_all
              convert: '0'
              duplicate: duplicate
          third_party_settings: {  }