#!/bin/bash

## Description: Export contents
## Usage: export-contents

rm -rf recipes/adesso_cms_starter/content
drush dcer node --property-name=type --property-value=page --folder=../recipes/adesso_cms_starter/content
drush dcer menu_link_content --folder=../recipes/adesso_cms_starter/content
drush dcer shortcut --folder=../recipes/adesso_cms_starter/content
