#!/bin/bash

## Description: Run yarn build:dev command
## Usage: watch
## Example: "ddev watch -- Read the HOW-TO.md for more commands"

yarn --cwd=web/themes/custom/adesso_standard install
yarn --cwd=web/themes/custom/adesso_standard dev