name: adesso CMS AI Suite
description: AI content generation and optimization with multiple providers (Anthropic, OpenAI, Groq) configured for adesso CMS
type: Site
recipes:
  # Base AI functionality from Drupal CMS
  - drupal_cms_ai

install:
  # Extended AI features
  - ai_ckeditor
  - ai_content_suggestions
  - ai_external_moderation
  - ai_translate
  - ai_image_alt_text
  - ai_image_bulk_alt_text
  - ai_provider_anthropic
  - ai_provider_openai

config:
  strict: false
  import:
    # AI module configurations
    ai: '*'
    ai_agents: '*'
    ai_assistant_api: '*'
    ai_ckeditor: '*'
    ai_content_suggestions: '*'
    ai_external_moderation: '*'
    ai_image_alt_text: '*'
    ai_logging: '*'
    ai_provider_anthropic: '*'
    ai_provider_groq: '*'
    ai_provider_openai: '*'
    ai_translate: '*'
    
  actions:
    # AI Configuration
    ai.settings:
      simpleConfigUpdate:
        provider: anthropic
        model: claude-3-5-sonnet-20241022
        temperature: 0.2
        max_tokens: 2048
        secret_key: _secure_key_managed_externally_
        
    ai_provider_anthropic.settings:
      simpleConfigUpdate:
        api_key: _secure_key_managed_externally_
        
    ai_provider_openai.settings:
      simpleConfigUpdate:
        api_key: _secure_key_managed_externally_
        
    ai_content_suggestions.settings:
      simpleConfigUpdate:
        enabled_entity_types:
          node:
            - page
            - news
            - event
            - person
            - project
        suggestions_count: 5
        auto_suggest: true
        
    ai_image_alt_text.settings:
      simpleConfigUpdate:
        enabled: true
        provider: anthropic
        batch_size: 10
        auto_generate: true
        
    # Content editor permissions for AI features
    user.role.content_editor:
      grantPermissions:
        - 'use ai content suggestions'
        - 'generate ai image alt text'