# BackstopJs service.
services:
  backstop:
    container_name: ddev-${DDEV_SITENAME}-backstop
    image: "backstopjs/backstopjs:6.3.23"
    init: true
    entrypoint: top -b
    volumes:
      - ../tests/backstop:/src
      - ../web/:/web
      - ".:/mnt/ddev_config:ro"
      - ddev-global-cache:/mnt/ddev-global-cache
    shm_size: 2gb
    labels:
         com.ddev.site-name: ${DDEV_SITENAME}
         com.ddev.approot: $DDEV_APPROOT
