name: adesso CMS SEO Advanced
description: Advanced SEO tools with Yoast integration, automated optimization, and comprehensive meta management
type: Site
recipes:
  # Base SEO functionality  
  - drupal_cms_seo_basic
  - drupal_cms_seo_tools

install:
  # Advanced SEO modules
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - yoast_seo
  - simple_sitemap
  - sitemap
  - robotstxt
  - seo_checklist

config:
  strict: false
  import:
    # SEO configurations
    metatag: '*'
    yoast_seo: '*'
    simple_sitemap: '*'
    robotstxt: '*'
    seo_checklist: '*'
    
  actions:
    # SEO Default Settings
    metatag.metatag_defaults.global:
      simpleConfigUpdate:
        tags.canonical_url: '[current-page:url]'
        tags.title: '[current-page:title] | [site:name]'
        tags.description: 'adesso CMS - Enterprise Drupal with AI Integration'
        
    metatag.metatag_defaults.node:
      simpleConfigUpdate:
        tags.abstract: '[node:summary]'
        tags.canonical_url: '[node:url]'
        tags.description: '[node:summary]'
        
    # Grant SEO permissions to content editors
    user.role.content_editor:
      grantPermissions:
        - 'edit meta tags'
        - 'administer yoast seo'
        - 'edit own yoast seo configuration'