name: Claude Issue Refinement & Enhancement

on:
  issues:
    types: [opened, reopened]
  issue_comment:
    types: [created]

jobs:
  enhance-issue:
    if: |
      (github.event_name == 'issues') ||
      (github.event_name == 'issue_comment' && 
       (contains(github.event.comment.body, '@claude-enhance') || 
        contains(github.event.comment.body, '/enhance-issue')))
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MCP Servers for Claude
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << 'EOF'
          {
            "mcpServers": {
              "github": {
                "command": "docker",
                "args": [
                  "run", "-i", "--rm",
                  "-e", "GITHUB_PERSONAL_ACCESS_TOKEN",
                  "ghcr.io/github/github-mcp-server:sha-efef8ae"
                ],
                "env": {
                  "GITHUB_PERSONAL_ACCESS_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
                }
              },
              "drupal": {
                "command": "docker",
                "args": [
                  "run", "-i", "--rm",
                  "-v", "${{ github.workspace }}:/workspace",
                  "ghcr.io/drupal/mcp-server:latest"
                ]
              }
            }
          }
          EOF

      - name: Create issue enhancement prompt
        run: |
          mkdir -p /tmp/claude-prompts
          cat > /tmp/claude-prompts/enhance-issue-prompt.txt << 'EOF'
          You are an expert issue analyst for ZH-DEMO, a Drupal 11.2.2 project for Canton Zurich municipal portals.
          
          Your task is to enhance GitHub issues by:
          1. Adding missing context and technical details
          2. Suggesting proper labels and categorization
          3. Breaking down complex issues into actionable tasks
          4. Adding relevant links to documentation or related issues
          5. Ensuring German compliance requirements (eCH-0059) are considered
          
          ## Project Context:
          - **Tech Stack**: Drupal 11.2.2, DDEV, TailwindCSS v4, Vite, Storybook
          - **Demo Municipality**: Gemeinde Bruchtal ("Leben am See")
          - **Compliance**: German government standards (eCH-0059)
          - **Key Features**: 15 paragraph types, 4 webforms, responsive design
          
          ## Available Tools:
          Use these MCP tools to gather context:
          - mcp__github__get_issue: Get current issue details
          - mcp__github__get_issue_comments: Review discussion context
          - mcp__github__search_issues: Find related issues for cross-referencing
          - mcp__github__update_issue: Apply enhancements (DO NOT post comments)
          - mcp__github__list_issues: Understand project issue patterns
          
          ## Enhancement Process:
          1. **Analyze Issue**: Get issue details and assess completeness
          2. **Research Context**: Search for related issues and patterns
          3. **Enhance Content**: Add technical details, acceptance criteria, or clarifications
          4. **Categorize**: Apply appropriate labels (bug, feature, enhancement, compliance)
          5. **Structure**: Break complex issues into sub-tasks if needed
          
          ## Focus Areas for Enhancement:
          - **Technical Clarity**: Add specific file paths, component names, configuration details
          - **Acceptance Criteria**: Define clear success conditions
          - **German Compliance**: Ensure accessibility and government standards are addressed
          - **Dependencies**: Identify related components, modules, or issues
          - **Testing Requirements**: Specify what needs validation
          
          ## Labels to Consider:
          - Priority: `high-priority`, `medium-priority`, `low-priority`
          - Type: `bug`, `feature`, `enhancement`, `documentation`, `compliance`
          - Area: `frontend`, `backend`, `drupal`, `performance`, `accessibility`
          - Status: `needs-triage`, `ready-for-development`, `blocked`
          
          **IMPORTANT**: Only update the issue itself - DO NOT post comments explaining your changes.
          Focus on making the issue more actionable and valuable for the development team.
          
          Issue to enhance:
          - Repository: ${{ github.repository }}
          - Issue Number: ${{ github.event.issue.number }}
          EOF

      - name: Run Claude Issue Enhancement
        uses: anthropics/claude-code-action@v1
        with:
          prompt: $(cat /tmp/claude-prompts/enhance-issue-prompt.txt)
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --allowedTools mcp__github__get_issue,mcp__github__get_issue_comments,mcp__github__search_issues,mcp__github__update_issue,mcp__github__list_issues
            --mcp-config /tmp/mcp-config/mcp-servers.json
            --max-turns 3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log enhancement completion
        run: |
          echo "✅ Issue #${{ github.event.issue.number }} has been enhanced by Claude"
          echo "Enhanced at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"