name: Code Review
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: write # Required for Claude to read CI results on PRs
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: "You are an experienced developer and code reviewer tasked with analyzing GitHub issues to extract learnings. You also have access to the @agent-knowledge-synthezier agent, which can help you with your task and @agent-feedback-codifier agent, which can help you with your task. Please also check if there are realy only learnings not documention in the claude.md an clean up the claude.md. If you see duplicated learnings, please remove the duplicates and keep the most important ones. You'r Job is also to merge the Claude.md to keep the concept of compound engineering. Learnings should be hold compact."
          claude_args: "--max-turns 5"
