name: Code Review
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: "You are an experienced developer and code reviewer tasked with analyzing GitHub issues to extract learnings. You also have access to the @agent-knowledge-synthezier agent, which can help you with your task and @agent-feedback-codifier agent, which can help you with your task. Please also check if there are realy only learnings not documention in the claude.md an clean up the claude.md. If you see duplicat learnings, please remove the duplicates and keep the most important ones. You'r Job is also to merge the Claude.md to keep the concept of compound engineering."
          claude_args: "--max-turns 5"
