name: Daily compact
on:
    schedule:
        - cron: "0 7 * * *"
jobs:
    compact:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            issues: write
            id-token: write
            actions: write # Required for Claude to read CI results on PRs
        steps:
            -   uses: anthropics/claude-code-action@v1
                with:
                  claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
                  prompt: "/flatten-rules"
                  claude_args: "--model claude-opus-4-1-20250805"